tests for setting up ossm console
kiali/openshift-servicemesh-plugin pull request #236
Opened 2024-01-13 00:23 UTC by ScriptingShrimp

2024-01-13 00:26 UTC, jmazzitelli commented
I believe this does what you want already : https://github.com/kiali/kiali/blob/master/hack/install-kiali-ossmc-openshift.sh

2024-01-16 00:29 UTC, ScriptingShrimp commented
> I believe this does what you want already : https://github.com/kiali/kiali/blob/master/hack/install-kiali-ossmc-openshift.sh

I checked the scripts, currently I will leave as it is (time concerns).  I'm not opposed to refactor this and consolidate into kiali/kiali and copy into this repo by `hack/copy-frontend-src-to-ossmc.sh`. Shall we file an issue?

2024-01-16 01:02 UTC, jmazzitelli requested changes

2024-01-16 01:02 UTC, jmazzitelli commented on hack/manage-ossmc.sh
> +    Wait for the OSSMC given pod to be ready.
```suggestion
    Wait for the OSSMC plugin pod to be ready. 
```

2024-01-16 01:02 UTC, jmazzitelli commented on hack/manage-ossmc.sh
> +    -v|--validate-ossmc)         validate-ossmc;                     exit $?; ;;
trivial... spacing:

```suggestion
    -v|--validate-ossmc)        validate-ossmc;                exit $?; ;;
```

2024-01-16 01:33 UTC, jmazzitelli approved these changes
I didn't run it, but the script looks good.

2024-01-16 08:20 UTC, ferhoyos approved these changes
LGTM, tested locally and works fine.

2024-01-16 13:45 UTC, merged