Ossmc regression extended
kiali/openshift-servicemesh-plugin pull request #244
Opened 2024-01-23 02:35 UTC by ScriptingShrimp

smoke testing for OCP workloads > deployments for presence of service mesh elements 

additional refactoring and naming conventions 

tested on OCP all passing

2024-01-23 16:24 UTC, ferhoyos requested changes
I have not tested it but code LGTM, just small comments.

2024-01-23 16:24 UTC, ferhoyos commented on plugin/cypress/e2e/featureFiles/workloads-deployments.feature
> +        And user is able to see WorkloadDescriptionCard with Kiali Workload
```suggestion
        When user clicks tab with "Overview" button
        Then user is able to see WorkloadDescriptionCard with Kiali Workload
```
Proper action here is `When`

2024-01-23 16:24 UTC, ferhoyos commented on plugin/cypress/e2e/featureFiles/workloads-deployments.feature
> +        Then user clicks tab with "Traffic" button
```suggestion
        When user clicks tab with "Traffic" button
```
Proper action here is `When`

2024-01-23 16:24 UTC, ferhoyos commented on plugin/cypress/e2e/workloads-deployments.ts
> +When('user is able to see WorkloadDescriptionCard with Kiali Workload', () => {
```suggestion
Then('user is able to see WorkloadDescriptionCard with Kiali Workload', () => {
```
Proper action here is `Then`

2024-01-23 16:24 UTC, ferhoyos commented on plugin/cypress/e2e/workloads-deployments.ts
> +When('user sees {string} dropdown', (dropdownText:string) => {
```suggestion
Then('user sees {string} dropdown', (dropdownText:string) => {
```
Proper action here is `Then`

2024-01-29 11:38 UTC, nrfox reviewed
LGTM but I'll let @ferhoyos approve since he's more familiar with OSSMC

2024-01-29 16:28 UTC, ferhoyos approved these changes
LGTM. They are additional steps to be added when bookinfo application can be installed on tests (https://github.com/kiali/openshift-servicemesh-plugin/pull/245), but this could be done as a separate PR.

2024-01-29 21:00 UTC, merged