WIP Graph kiosk links
kiali/openshift-servicemesh-plugin pull request #27
Opened 2022-06-17 13:02 UTC by lucasponce

WIP for https://github.com/kiali/openshift-servicemesh-plugin/issues/21
Not finished as it requires https://github.com/kiali/openshift-servicemesh-plugin/pull/24

2022-06-17 13:19 UTC, jmazzitelli commented
One thing that we will need to address (probably not in the PR - maybe I should write up a separate issue?) is that we need these links to support multi-tenancy.

OSSM can create multiple control planes in a cluster, and Kiali is installed in each of them. We need the plugin to talk to the correct Kiali.

Right now, the plugin relies on the single config setting kiali.url. However, that should only be the fallback URL (in the case of `accessible_namespaces = [**]` for example). But for the actual OSSM use case, we should look at the namespace labels, determine which Kiali is associated with that namespace and then we can get its route from that.

The Kiali operator will label each namespace with a kiali-specific label that identifies the Kiali that accesses that namespace. From that name identifier, we should be able to find the route.

@lucasponce I don't think this is related to this PR - so should I write this up as a separate issue? Or do you want to do this in this PR, too?

2022-06-17 13:23 UTC, lucasponce commented
> One thing that we will need to address (probably not in the PR - maybe I should write up a separate issue?) is that we need these links to support multi-tenancy.

Well, more than links to me multi-tenancy is a news story that we need to figure out how to address it. We discussed with Jamie and Andrew that is not bad to assume a single mesh per cluster in these first steps.

Because the plugin would need also to have visibility of the multi-tenant installation as a concept to see how to deal with one or another.

It's a good point and we can open a story for it but I think that when we have a robust use case for single cluster + single mesh, the plugin could be ready to collect users' feedback.

2022-06-17 13:33 UTC, lucasponce commented
> so should I write this up as a separate issue? Or do you want to do this in this PR, too?

+1 we can put it in the backlog, no problem on that.

2022-06-23 11:14 UTC, lucasponce commented
This PR and this https://github.com/kiali/kiali/pull/5223 are ready to be tested together.

A small demo about the scope of these new capabilities:
![plugin-graph-links](https://user-images.githubusercontent.com/1662329/175286100-093017f2-a814-426e-80c4-bdd2cd37ed04.gif)
r

2022-06-23 18:31 UTC, leandroberetta approved these changes
Tested locally, works good!.

2022-06-23 18:31 UTC, leandroberetta commented on plugin/src/utils.ts
> +                console.log('TODELETE detailUrl: ' + detailUrl);
All this reminders needs to be deleted on this PR?.

2022-06-23 19:27 UTC, jmazzitelli requested changes
need to remove those temporary debug log messages

Aside from that, this all runs good. We can merge this after those "TODELETE" log messages are removed

2022-06-23 19:27 UTC, jmazzitelli commented on plugin/src/utils.ts
> +                console.log('TODELETE webParams: '+ webParams);
```suggestion
```

2022-06-23 19:27 UTC, jmazzitelli commented on plugin/src/utils.ts
> +                console.log('TODELETE namespace: '+ namespace);
```suggestion
```

2022-06-23 19:27 UTC, jmazzitelli commented on plugin/src/utils.ts
> +                console.log('TODELETE detail: '+ detail);
```suggestion
```

2022-06-23 19:27 UTC, jmazzitelli commented on plugin/src/utils.ts
> +                console.log('TODELETE detailUrl: ' + detailUrl);
```suggestion
```

2022-06-24 12:31 UTC, jmazzitelli approved these changes

2022-06-24 13:47 UTC, merged